# Generated by Django 3.2.23 on 2024-11-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20241104_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
    ]
