# Generated by Django 3.2.23 on 2024-11-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debatehub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debate',
            old_name='creator',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='debate',
            name='title',
        ),
        migrations.AddField(
            model_name='debate',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
