# Generated by Django 3.2.23 on 2024-11-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debatehub', '0002_auto_20241105_0438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
